
const CONTEXT_API = 'v1';

const ID_MESSAGES_ERROR = {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_BLOCKED: 'USER_BLOCKED',

    INVALID_PASSWORD: 'INVALID_PASSWORD',
    RESET_PASSWORD_REQ: 'RESET_PASSWORD_REQ',

    TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
}

export {
    CONTEXT_API, ID_MESSAGES_ERROR
};

